[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com https://m.stripe.network;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://m.stripe.network;
      font-src 'self' data: https://fonts.gstatic.com https://m.stripe.network;
      img-src 'self' data: https: http:;
      connect-src 'self' https://*.supabase.co https://api.stripe.com https://m.stripe.network;
      frame-src 'self' https://js.stripe.com https://hooks.stripe.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    """

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
